import autoTable from "jspdf-autotable";
import cymsLogo from "../assets/cyms-logo.png";

const PDF_COLORS = {
  text: [15, 23, 42],
  muted: [100, 116, 139],
  border: [226, 232, 240],
  primary: [37, 99, 235],
  primarySoft: [239, 246, 255],
  success: [22, 163, 74],
  warning: [245, 158, 11],
  danger: [239, 68, 68],
  white: [255, 255, 255],
  rowAlt: [248, 250, 252],
};

export function addPdfHeader(doc, title, subtitle = "Professional system-generated report") {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.addImage(cymsLogo, "PNG", 14, 10, 34, 16);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...PDF_COLORS.text);
  doc.text("Construction Yard Management System", 52, 15.5);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12.5);
  doc.setTextColor(...PDF_COLORS.primary);
  doc.text(title, 52, 23.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...PDF_COLORS.muted);
  doc.text(subtitle, 52, 29);

  doc.setDrawColor(...PDF_COLORS.border);
  doc.setLineWidth(0.4);
  doc.line(14, 36, pageWidth - 14, 36);
}

export function addPdfFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);

    doc.setDrawColor(...PDF_COLORS.border);
    doc.setLineWidth(0.3);
    doc.line(14, pageHeight - 18, pageWidth - 14, pageHeight - 18);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...PDF_COLORS.muted);

    doc.text(
      "Generated by CYMS • Construction Yard Management System",
      14,
      pageHeight - 10
    );

    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 38, pageHeight - 10);
  }
}

export function addPdfTable(doc, { startY, head, body, margin = 14 }) {
  autoTable(doc, {
    startY,
    head,
    body,
    theme: "grid",
    margin: { left: margin, right: margin, bottom: 24 },
    styles: {
      font: "helvetica",
      fontSize: 8.7,
      cellPadding: { top: 4, right: 4, bottom: 4, left: 4 },
      textColor: PDF_COLORS.text,
      lineColor: PDF_COLORS.border,
      lineWidth: 0.25,
      valign: "middle",
    },
    headStyles: {
      fillColor: PDF_COLORS.primary,
      textColor: PDF_COLORS.white,
      fontStyle: "bold",
      fontSize: 9.2,
      halign: "left",
    },
    bodyStyles: {
      fillColor: PDF_COLORS.white,
    },
    alternateRowStyles: {
      fillColor: PDF_COLORS.rowAlt,
    },
    didDrawPage: () => {
      // Footer is added after all tables using addPdfFooter()
    },
  });
}

export function addPdfSectionTitle(doc, title, y) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11.5);
  doc.setTextColor(...PDF_COLORS.text);
  doc.text(title, 14, y);
}

export function addPdfMetaSection(doc, rows, startY = 44) {
  autoTable(doc, {
    startY,
    theme: "plain",
    margin: { left: 14, right: 14 },
    body: rows,
    styles: {
      font: "helvetica",
      fontSize: 9,
      cellPadding: { top: 2.8, right: 4, bottom: 2.8, left: 0 },
      textColor: PDF_COLORS.text,
    },
    columnStyles: {
      0: {
        fontStyle: "bold",
        textColor: PDF_COLORS.muted,
        cellWidth: 38,
      },
      1: {
        textColor: PDF_COLORS.text,
      },
    },
  });
}

export function addStatusBadge(doc, status, x, y) {
  const normalized = String(status || "N/A").toUpperCase();

  let color = PDF_COLORS.muted;
  let bg = [241, 245, 249];

  if (normalized === "APPROVED" || normalized === "AVAILABLE") {
    color = PDF_COLORS.success;
    bg = [240, 253, 244];
  }

  if (normalized === "PENDING" || normalized === "ISSUED") {
    color = PDF_COLORS.warning;
    bg = [255, 251, 235];
  }

  if (normalized === "REJECTED" || normalized === "RETIRED") {
    color = PDF_COLORS.danger;
    bg = [254, 242, 242];
  }

  if (normalized === "MAINTENANCE") {
    color = [139, 92, 246];
    bg = [245, 243, 255];
  }

  const textWidth = doc.getTextWidth(normalized);
  const badgeWidth = textWidth + 10;

  doc.setFillColor(...bg);
  doc.roundedRect(x, y - 5, badgeWidth, 8, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...color);
  doc.text(normalized, x + 5, y);
}